/**
 * Image sourcing service — provider priority:
 *   client setting 'dalle'  → DALL-E 3 only (AI-generated, bespoke)
 *   client setting 'stock'  → Pexels → Pixabay → Unsplash
 *   client setting 'auto'   → DALL-E 3 (if key set) → Pexels → Pixabay → Unsplash
 *   client setting 'none'   → skip images entirely
 *
 * All providers are best-effort — failures never block WordPress publishing.
 */

export interface SourcedImage {
  downloadUrl: string
  alt: string
  credit: string        // e.g. "Photo by Jane on Pexels" or "AI-generated image"
  creditHtml: string    // HTML version for WP caption
}

// ─── DALL-E 3 ────────────────────────────────────────────────────────────────

export async function generateWithDalle(
  title: string,
  industry: string,
  excerpt: string
): Promise<SourcedImage | null> {
  const key = process.env.OPENAI_API_KEY
  if (!key) return null

  try {
    // Craft a prompt tuned for blog featured images
    const prompt = [
      `Create a professional, eye-catching blog featured image for an article titled "${title}".`,
      `The business is in the ${industry} industry.`,
      excerpt ? `Context: ${excerpt.slice(0, 200)}` : '',
      'Style: high-quality commercial photography or editorial illustration.',
      'Requirements: landscape orientation, no text, no watermarks, no logos.',
      'Mood: professional, engaging, relevant to the topic.',
    ].filter(Boolean).join(' ')

    const res = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${key}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt,
        n: 1,
        size: '1792x1024',   // landscape, ideal for featured images
        quality: 'standard', // 'hd' is 2× the cost — upgrade per-client if needed
      }),
    })

    if (!res.ok) {
      const err = await res.json().catch(() => ({})) as any
      console.error('[images] DALL-E error:', err.error?.message || res.status)
      return null
    }

    const data = await res.json() as any
    const url = data.data?.[0]?.url
    if (!url) return null

    return {
      downloadUrl: url,
      alt: `AI-generated featured image for: ${title}`,
      credit: 'AI-generated image',
      creditHtml: 'Image generated by DALL·E 3',
    }
  } catch (e) {
    console.error('[images] DALL-E exception:', e)
    return null
  }
}

// ─── Pexels ──────────────────────────────────────────────────────────────────

async function searchPexels(query: string): Promise<SourcedImage | null> {
  const key = process.env.PEXELS_API_KEY
  if (!key) return null

  try {
    const res = await fetch(
      `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`,
      { headers: { Authorization: key } }
    )
    if (!res.ok) return null

    const data = await res.json() as any
    const photo = data.photos?.[0]
    if (!photo) return null

    return {
      downloadUrl: photo.src.large2x || photo.src.large,
      alt: photo.alt || query,
      credit: `Photo by ${photo.photographer} on Pexels`,
      creditHtml: `Photo by <a href="${photo.photographer_url}" target="_blank" rel="noopener">${photo.photographer}</a> on <a href="https://www.pexels.com" target="_blank" rel="noopener">Pexels</a>`,
    }
  } catch (err) {
    console.debug('[images] Pexels search failed:', (err as Error).message)
    return null
  }
}

// ─── Pixabay ─────────────────────────────────────────────────────────────────

async function searchPixabay(query: string): Promise<SourcedImage | null> {
  const key = process.env.PIXABAY_API_KEY
  if (!key) return null

  try {
    const res = await fetch(
      `https://pixabay.com/api/?key=${key}&q=${encodeURIComponent(query)}&image_type=photo&orientation=horizontal&per_page=3&safesearch=true&min_width=1200`
    )
    if (!res.ok) return null

    const data = await res.json() as any
    const photo = data.hits?.[0]
    if (!photo) return null

    return {
      downloadUrl: photo.largeImageURL,
      alt: photo.tags || query,
      credit: `Photo by ${photo.user} on Pixabay`,
      creditHtml: `Photo by <a href="https://pixabay.com/users/${photo.user}-${photo.user_id}/" target="_blank" rel="noopener">${photo.user}</a> on <a href="https://pixabay.com" target="_blank" rel="noopener">Pixabay</a>`,
    }
  } catch (err) {
    console.debug('[images] Pixabay search failed:', (err as Error).message)
    return null
  }
}

// ─── Unsplash (kept for backwards compat) ───────────────────────────────────

async function searchUnsplash(query: string): Promise<SourcedImage | null> {
  const key = process.env.UNSPLASH_ACCESS_KEY
  if (!key) return null

  try {
    const res = await fetch(
      `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape&client_id=${key}`
    )
    if (!res.ok) return null

    const data = await res.json() as any
    const photo = data.results?.[0]
    if (!photo) return null

    // Required by Unsplash API guidelines
    fetch(`${photo.links.download_location}&client_id=${key}`).catch(() => {
      console.debug('[images] Unsplash download tracker failed (non-critical)')
    })

    return {
      downloadUrl: photo.urls.regular,
      alt: photo.alt_description || query,
      credit: `Photo by ${photo.user.name} on Unsplash`,
      creditHtml: `Photo by <a href="${photo.user.links.html}?utm_source=bcp&utm_medium=referral" target="_blank" rel="noopener">${photo.user.name}</a> on <a href="https://unsplash.com?utm_source=bcp&utm_medium=referral" target="_blank" rel="noopener">Unsplash</a>`,
    }
  } catch (err) {
    console.debug('[images] Unsplash search failed:', (err as Error).message)
    return null
  }
}

// ─── Orchestrator ────────────────────────────────────────────────────────────

/**
 * Fetch an image for a blog post according to the client's preferred source.
 * Returns null if no provider is configured or all fail.
 */
export async function getImageForPost(opts: {
  title: string
  industry: string
  excerpt: string
  imageSource: string   // 'auto' | 'dalle' | 'stock' | 'none'
  searchQuery?: string  // Pre-built query (Claude's IMAGE_QUERY, client keywords, or cleaned title)
}): Promise<SourcedImage | null> {
  const { title, industry, excerpt, imageSource } = opts
  const searchQuery = opts.searchQuery || `${title} ${industry}`.slice(0, 120)

  if (imageSource === 'none') return null
  if (imageSource === 'dalle') {
    return generateWithDalle(title, industry, excerpt)
  }

  if (imageSource === 'stock') {
    return (
      (await searchPexels(searchQuery)) ??
      (await searchPixabay(searchQuery)) ??
      (await searchUnsplash(searchQuery))
    )
  }

  // 'auto' — DALL-E first (if available), then stock cascade
  if (process.env.OPENAI_API_KEY) {
    const dalleImage = await generateWithDalle(title, industry, excerpt)
    if (dalleImage) return dalleImage
  }

  return (
    (await searchPexels(searchQuery)) ??
    (await searchPixabay(searchQuery)) ??
    (await searchUnsplash(searchQuery))
  )
}

// ─── WordPress media upload ───────────────────────────────────────────────────

/**
 * Downloads an image and uploads it to a WordPress media library.
 * Returns the WP media ID, or null if anything fails.
 */
export async function uploadImageToWordPress(
  image: SourcedImage,
  slug: string,
  wpUrl: string,
  credentials: string
): Promise<number | null> {
  try {
    const imgRes = await fetch(image.downloadUrl)
    if (!imgRes.ok) return null

    const contentType = imgRes.headers.get('content-type') || 'image/jpeg'
    const ext = contentType.includes('png') ? 'png' : contentType.includes('webp') ? 'webp' : 'jpg'
    const imageBuffer = await imgRes.arrayBuffer()

    const uploadRes = await fetch(`${wpUrl}/wp-json/wp/v2/media`, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${credentials}`,
        'Content-Disposition': `attachment; filename="${slug}.${ext}"`,
        'Content-Type': contentType,
      },
      body: imageBuffer,
    })

    if (!uploadRes.ok) return null
    const media = await uploadRes.json() as any

    // Set alt text + attribution caption (non-critical)
    fetch(`${wpUrl}/wp-json/wp/v2/media/${media.id}`, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${credentials}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        alt_text: image.alt,
        caption: image.creditHtml,
      }),
    }).catch(() => {
      console.debug('[images] WordPress media alt/caption update failed (non-critical)')
    })

    return media.id
  } catch (err) {
    console.warn('[images] WordPress media upload failed:', (err as Error).message)
    return null
  }
}
