// @ts-nocheck
// Niche report worker — generates a multi-section lead-magnet report for a
// single `reports` row. Unlike pSEO which batches across locations, each
// report_generate job produces ONE long-form document.
//
// Job params shape (set by POST /api/jobs/report):
// {
//   report_id: string,
//   template_id: string,
//   extra_vars?: Record<string,string>,
// }
import db from '../db.js'
import { getClient } from './claude.js'
import { complianceGuardPrompt, effectiveBlockList } from './compliance.js'

async function generateBatch(prompt: string): Promise<string> {
  const response = await getClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 8192,        // reports are longer than pSEO pages
    thinking: { type: 'adaptive' } as any,
    messages: [{ role: 'user', content: prompt }]
  })
  return response.content
    .filter((b: any) => b.type === 'text')
    .map((b: any) => b.text)
    .join('')
}

function extractTitle(text: string): string {
  const match = text.match(/^#\s+(.+)/m)
  return match ? match[1].trim() : text.split('\n')[0].slice(0, 120).trim()
}

function extractImageQuery(text: string): { body: string; imageQuery: string } {
  const match = text.match(/\nIMAGE_QUERY:\s*(.+)$/m)
  if (!match) return { body: text.trim(), imageQuery: '' }
  return { body: text.slice(0, match.index).trim(), imageQuery: match[1].trim() }
}

// Extract a "HERO:" block if the model produced one — used as landing-page copy.
function extractHero(text: string): { hero: string; rest: string } {
  const match = text.match(/^HERO:\s*([\s\S]+?)\n---\s*$/m)
  if (!match) return { hero: '', rest: text }
  return { hero: match[1].trim(), rest: text.slice(match.index + match[0].length).trim() }
}

function renderTemplate(tpl: string, values: Record<string, string>): string {
  return tpl.replace(/\{([a-z0-9_]+)\}/gi, (m, key) => {
    const v = values[key.toLowerCase()]
    return v !== undefined && v !== '' ? v : m
  })
}

// Convert the report markdown to a styled HTML document suitable for post-capture delivery.
// Report aesthetic: magazine-style, more editorial than a blog post.
function markdownToReportHtml(md: string, title: string): string {
  const body = md
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^\* (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*?<\/li>)(\n<li>)/g, '$1$2')  // join adjacent list items
    .replace(/(<li>[\s\S]+?<\/li>)(?!\n<li>)/g, '<ul>$1</ul>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\n\n/g, '</p><p>')

  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>${title}</title>
<style>
  :root { --ink:#0f172a; --accent:#d97706; --muted:#64748b; --bg:#fdfcf8; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 760px; margin: 0 auto; padding: 60px 24px 80px; color: var(--ink); line-height: 1.75; background: var(--bg); }
  h1 { font-size: 2.4rem; line-height: 1.2; margin: 0 0 16px; border-bottom: 3px solid var(--accent); padding-bottom: 14px; }
  h2 { font-size: 1.5rem; margin-top: 48px; color: #1e3a5f; }
  h3 { font-size: 1.15rem; margin-top: 32px; color: #334155; }
  p { margin: 1em 0; }
  ul { padding-left: 22px; }
  li { margin: 6px 0; }
  strong { color: var(--ink); }
  em { color: var(--muted); }
  .report-footer { margin-top: 80px; padding-top: 24px; border-top: 1px solid #e2e8f0; font-size: 0.85rem; color: var(--muted); }
</style></head><body><p>${body}</p>
<div class="report-footer">Report generated by βWave · aim.report</div>
</body></html>`
}

export async function runReportJob(jobId: string): Promise<void> {
  const job = db.prepare('SELECT * FROM jobs WHERE id = ?').get(jobId) as any
  if (!job) throw new Error(`Job ${jobId} not found`)
  if (job.status !== 'pending') return

  const params = JSON.parse(job.params || '{}')
  const { report_id, template_id, extra_vars = {} } = params

  db.prepare(`UPDATE jobs SET status = 'running', started_at = unixepoch(), total = 1 WHERE id = ?`).run(jobId)

  const report = db.prepare('SELECT * FROM reports WHERE id = ?').get(report_id) as any
  if (!report) {
    db.prepare(`UPDATE jobs SET status = 'failed', error = ?, completed_at = unixepoch() WHERE id = ?`)
      .run(`Report ${report_id} not found`, jobId)
    return
  }

  const template = db.prepare('SELECT * FROM templates WHERE id = ?').get(template_id) as any
  if (!template) {
    db.prepare(`UPDATE jobs SET status = 'failed', error = ?, completed_at = unixepoch() WHERE id = ?`)
      .run(`Template ${template_id} not found`, jobId)
    return
  }

  // Client is optional — aim.report itself may generate un-attributed reports.
  const client = job.client_id
    ? db.prepare('SELECT * FROM clients WHERE id = ?').get(job.client_id) as any
    : null
  if (client) {
    client.expertise_areas = JSON.parse(client.expertise_areas || '[]')
    client.blocked_topics = JSON.parse(client.blocked_topics || '[]')
  }

  try {
    const values: Record<string, string> = {
      niche: report.niche,
      title: report.title,
      subtitle: report.subtitle || '',
      business: client?.business_name || 'aim.report',
      business_name: client?.business_name || 'aim.report',
      industry: client?.industry || report.niche,
      tone: client?.tone_of_voice || 'authoritative',
      audience: client?.target_audience || `professionals in the ${report.niche} space`,
      ...extra_vars,
    }
    const renderedBody = renderTemplate(template.prompt_template, values)
    const guard = complianceGuardPrompt(effectiveBlockList(client?.blocked_topics))

    // We ask for HERO: ... --- then the full report so a single call produces both
    // landing-page copy and the deliverable report in one pass.
    const prompt = `${renderedBody}

FORMAT (strict):
- Start with:
HERO:
[2–3 sentence punchy pitch for the landing page — why they should download this]
---
- Then: # [Report title]
- Short executive summary paragraph
- 5–7 sections with ## headings, each with 2–4 paragraphs plus a short insight or bullet list
- Close with a "## Key takeaways" section of 4–6 bullet points
- Very last line: IMAGE_QUERY: [2–4 words for a cover image]

Write only the HERO block, the report body, and the IMAGE_QUERY line. No preamble.${guard}`

    const raw = await generateBatch(prompt)

    if (raw.startsWith('COMPLIANCE_BLOCK:')) {
      db.prepare(`UPDATE jobs SET status = 'failed', failed = 1, error = ?, completed_at = unixepoch() WHERE id = ?`)
        .run(raw.slice(0, 200), jobId)
      return
    }

    const { hero, rest } = extractHero(raw)
    const { body: cleanBody, imageQuery } = extractImageQuery(rest)
    const title = extractTitle(cleanBody) || report.title
    const html = markdownToReportHtml(cleanBody, title)

    db.prepare(`
      UPDATE reports
      SET title = ?, hero_copy = ?, body_md = ?, body_html = ?, image_query = ?, status = 'draft', updated_at = unixepoch()
      WHERE id = ?
    `).run(title, hero, cleanBody, html, imageQuery, report_id)

    db.prepare(`
      UPDATE jobs SET status = 'complete', completed = 1, completed_at = unixepoch(), result = ?
      WHERE id = ?
    `).run(JSON.stringify({ report_id, title, hero_chars: hero.length, body_chars: cleanBody.length }), jobId)

    console.log(`[report] Generated "${title}" (${cleanBody.length} chars) for niche "${report.niche}"`)
  } catch (err: any) {
    console.error(`[report] Job ${jobId} failed: ${err.message}`)
    db.prepare(`UPDATE jobs SET status = 'failed', failed = 1, error = ?, completed_at = unixepoch() WHERE id = ?`)
      .run(err.message || String(err), jobId)
  }
}
